const mongoose = require('mongoose');
const requireLogin = require('../middlewares/requireLogin');
const requireCredits = require('../middlewares/requireCredits');

// Sidestep issue with running potential tests
const Survey = mongoose.model('surveys');

module.exports = app => {
	// Verify that user is logged in &
	// verify that they have enough credits
	app.post('/api/surveys', requireLogin, requireCredits, (req, res) => {
		// Pull properties from req.body
		const { title, subject, body, recipients } = req.body;

		// Create a new Survey
		const survey = Survey({
			title,
			subject,
			body,
			recipients: recipients.split(',').map(email => ({
				email: email.trim()
			})),
			// ID generated by Mongoose
			_user: req.user.id,
			dateSent: Date.now()
		});
	});
};
